<script src="<?= BASE_URL . 'other_assets/js/jquery.js' ?>"></script>
<script src="<?= BASE_URL . 'other_assets/js/jquery.easing.1.3.js' ?>"></script>
<script src="<?= BASE_URL . 'other_assets/js/bootstrap.min.js' ?>"></script>
<script src="<?= BASE_URL . 'other_assets/js/jquery.fancybox.pack.js' ?>"></script>
<script src="<?= BASE_URL . 'other_assets/js/jquery.fancybox-media.js' ?>"></script>
<script src="<?= BASE_URL . 'other_assets/js/js/google-code-prettify/prettify.js' ?>"></script>
<script src="<?= BASE_URL . 'other_assets/js/portfolio/jquery.quicksand.js' ?>"></script>
<script src="<?= BASE_URL . 'other_assets/js/js/portfolio/setting.js' ?>"></script>
<script src="<?= BASE_URL . 'other_assets/js/jquery.flexslider.js' ?>"></script>
<script src="<?= BASE_URL . 'other_assets/js/animate.js' ?>"></script>
<script src="<?= BASE_URL . 'other_assets/js/custom.js' ?>"></script>